Lab refactor
Pitt-CSC/PittAPI pull request #159
Opened 2024-04-16 16:51 UTC by Steven-Jarmell

The old way of retrieving lab data was broken so I had to refactor the method/tests to be up to date.

I also had a previous commit for the people tests that I had to revert.

2024-05-22 23:18 UTC, tianyizheng02 requested changes

2024-05-22 23:18 UTC, tianyizheng02 commented on tests/people_test.py
We actually don't wanna revert `tests/people_tests.py` back to what it was before, because we need the tests to be mocked in order for them to pass as expected (see #166). Could you undo the changes you made to this file in this PR so that we keep the mocked tests?

2024-05-22 23:18 UTC, tianyizheng02 commented
Contributes to #166

2024-07-01 01:03 UTC, Steven-Jarmell commented
@tianyizheng02 Hey sorry, I have not checked this and had the emails going to my Pitt email. I can still fix this, but it looks like you rewrote the lab.py file anyways, so let me know if we should close this CR or what you would like!

2024-07-03 03:46 UTC, tianyizheng02 commented
Hey @Steven-Jarmell, thanks for coming back to this. Yes, I and another contributor had modified the `lab.py` file since you published this PR, but the changes that conflict with your PR are mostly minor formatting stuff. Your PR is still fine to keep, so long as we fix the minor merge conflicts. I just took the liberty of fixing most of them.

The only remaining issue is a `match` statement in your code (we're testing the codebase on Python 3.9 now, which doesn't support `match` statements). I'll quickly fix that in a moment.

Once I fix all the merge conflicts and the testing workflows are passing, can you take a look at your PR to make sure that I didn't mess anything up?

2024-07-03 04:57 UTC, Steven-Jarmell reviewed
LGTM

2024-07-03 04:58 UTC, tianyizheng02 approved these changes

2024-07-03 04:58 UTC, merged