Gym module created
Pitt-CSC/PittAPI pull request #185
Opened 2024-06-28 22:10 UTC by csidarous

Created Gym module to scrape data of all the gym counts and returns as a dictionary.

2024-06-29 18:41 UTC, tianyizheng02 commented
Tests are failing because of formatting issues with `black`. Please check out the [contributing guidelines](https://github.com/pittcsc/PittAPI/blob/dev/CONTRIBUTING.md) for installing and running the dev tools we use. Ideally you should be using pre-commit to check for spacing issues, formatting issues, etc. prior to committing your code.

2024-06-29 18:42 UTC, tianyizheng02 requested changes
Please add unit tests for this new module

2024-06-29 18:42 UTC, tianyizheng02 commented on pittapi/gym.py
> +def _fetch_gym_info():
The leading underscore means that this is an internal function and not meant for the public API. Is this function supposed to be public?

Also, please type hint this function

2024-07-01 01:01 UTC, Steven-Jarmell commented
I have a lot of historical data for this stored, feel free to use this URL to access it: https://pitt-gym-tracker.vercel.app/api/gymdata/Baierl%20Rec%20Center

2024-07-06 01:12 UTC, csidarous commented on pittapi/gym.py
> +def _fetch_gym_info():
I made the changes and pushed again. Let me know if there is anything else to add. Iw ill most likely add more tests this coming week.

2024-07-06 05:01 UTC, Steven-Jarmell commented on pittapi/gym.py
> +    return info["Pitt Sports Dome"]
This is not a very scalable way of doing this and produces a lot of unnecessary code. Let's refactor this to have a list of gym names and one method to retrieve one gyms information. Something like this:

GYM_NAMES = ["Baierl Rec Center"... ]

def get_gym_information(gym_name: string) -> Gym:
     // Validate that gym_name is in GYM_NAMES
     // return info[gym_name]

With something like this, if there is ever a new gym location in the future that Pitt starts collecting data for, adding it to this API would be as simple as adding the name to the list, rather than having to create a brand new method for it.

It would also be a good practice to create a Gym data structure (as shown in the method signature) to store the information for each gym to create a formal model of how to access the data rather than having to print out the object and figure it out.

2024-07-06 05:08 UTC, Steven-Jarmell commented on pittapi/gym.py
> +def fetch_gym_info() -> dict:
Let's rename this, it can be misinterpreted as fetching a single gym's information. Let's also call it something like get_all_gyms_info()

2024-07-06 05:08 UTC, Steven-Jarmell commented on pittapi/gym.py
> +    return info["Pitt Sports Dome"]
This is not a very scalable way of doing this and produces a lot of unnecessary code. Let's refactor this to have a list of gym names and one method to retrieve one gyms information. Something like this:

GYM_NAMES = ["Baierl Rec Center"... ]

def get_gym_information(gym_name: string) -> Gym:
     // Validate that gym_name is in GYM_NAMES
     // return info[gym_name]

With something like this, if there is ever a new gym location in the future that Pitt starts collecting data for, adding it to this API would be as simple as adding the name to the list, rather than having to create a brand new method for it.

It would also be a good practice to create a Gym data structure (as shown in the method signature) to store the information for each gym to create a formal model of how to access the data rather than having to print out the object and figure it out.

2024-07-06 05:08 UTC, Steven-Jarmell commented on tests/gym_test.py
> +GYM_URL = "https://connect2concepts.com/connect2/?type=bar&key=17c2cbcb-ec92-4178-a5f5-c4860330aea0"
No need to declare this again, you can simply access it from the gym module :)

gym.GYM_URL

2024-07-06 05:08 UTC, Steven-Jarmell commented on tests/gym_test.py
> +        mock_html = """
Let's remove this mocked data and move it to the mocks folder.

2024-07-06 05:11 UTC, tianyizheng02 commented on pittapi/gym.py
> +    return info["Pitt Sports Dome"]
^ See `courses.py` for how you could create a data structure (namely a `NamedTuple`) to store this kind of structured data

2024-07-06 05:16 UTC, tianyizheng02 requested changes

2024-07-06 05:16 UTC, tianyizheng02 commented on pittapi/gym.py
> +def fetch_gym_info() -> dict:
Also on this line, it'd be nice if the type hint specified the dictionary's key and value types, something like
```py
def function_name() -> dict[some_type, some_type]:
```
If/when we start using `mypy` in this repo for static type checking, this'll be important

2024-07-06 05:18 UTC, tianyizheng02 commented
Also, looks like unit tests are failing:
```py
>       self.assertEqual(gym_info["Baierl Rec Center"], "200")
E       AssertionError: '0' != '200'
E       - 0
E       + 200
```
You can find more details in the test logs

2024-07-10 19:34 UTC, csidarous commented
Thanks both for your feedback and guidance. I will try my best to add more tests.

2024-07-11 03:27 UTC, Steven-Jarmell requested changes
One small change needed to fix the variable for the list of gym names, then this should be good

2024-07-11 03:27 UTC, Steven-Jarmell commented on pittapi/gym.py
> +GYM_Names = [
Should be GYM_NAMES

2024-07-14 05:16 UTC, tianyizheng02 requested changes

2024-07-14 05:16 UTC, tianyizheng02 commented on pittapi/gym.py
> +]
For clarify, can we move this const list to the top of the file, just below `GYM_URL`?

2024-07-14 05:16 UTC, tianyizheng02 commented on pittapi/gym.py
> +def get_all_gyms_info() -> List[Gym]:
Let's use the built-in `list` annotation rather than the imported `List`. Since this built-in annotation wasn't available until 3.10 (and we're trying to support 3.9), make sure to import `annotations` from `__future__`:
```suggestion
from __future__ import annotations

from bs4 import BeautifulSoup
import requests
from typing import NamedTuple

GYM_URL = "https://connect2concepts.com/connect2/?type=bar&key=17c2cbcb-ec92-4178-a5f5-c4860330aea0"


class Gym(NamedTuple):
    name: str
    date: str
    count: int
    percentage: int


def get_all_gyms_info() -> list[Gym]:
```

2024-07-14 05:16 UTC, tianyizheng02 commented on pittapi/gym.py
> +        return None
The return type of this function is `Gym | None`, since it returns `None` the gym name is invalid:
```suggestion
def get_gym_information(gym_name: str) -> Gym | None:
    """Fetches the information of a singular gym as a tuple"""
    info = get_all_gyms_info()
    if gym_name in GYM_NAMES:
        for gym in info:
            if gym.name == gym_name:
                return gym
    else:
        return None
```

2024-07-14 19:35 UTC, csidarous commented on pittapi/gym.py
> +        return None
Just made these changes! Let me know if there are any more changes to be made

2024-08-04 19:59 UTC, tianyizheng02 requested changes

2024-08-04 19:59 UTC, tianyizheng02 commented on pittapi/gym.py
> +        return None
```suggestion
    return None
```
The final `return` statement shouldn't be in an `else` clause. If the for-loop above ran to completion without returning any `Gym`, then this final return wouldn't run.

2024-08-04 19:59 UTC, tianyizheng02 commented on pittapi/gym.py
> +            percentage = 0
Could you add another unit test that tests for this case?

2024-08-04 19:59 UTC, tianyizheng02 commented on pittapi/gym.py
> +        return None
Could you add test cases for
1. when `gym_name` is not a valid gym name
2. when `gym_name` is a valid gym name but there's no info for that gym

2024-08-04 20:17 UTC, tianyizheng02 requested changes

2024-08-04 20:17 UTC, tianyizheng02 commented on pittapi/gym.py
> +            percentage = 0
I think it'd be better if this string-parsing logic was refactored into a separate function, preferably as a `classmethod` of the `Gym` class:
1. This new function would effectively act as a constructor for `Gym` that takes a single string as input. Doing this would significantly simplify the logic of this function:
    ```py
    gyms = [
        Gym.from_str(gym.get_text("|", strip=True))
        for gym in gym_info_list
    ]
    ```
2. Keeping the info-parsing logic separate from the info-fetching logic makes unit testing much easier. Right now, `get_all_gyms_info` does both the task of fetching the gym info as well as the task of parsing the gym info, so you can't test each of those components separately. If you wanted to test whether `get_all_gyms_info` is parsing the gym info correctly, you'd need to mock an HTTP request just to do so, and you'd only be testing the input strings within that specific mock. By comparison, if the info-parsing logic was in a separate function, you could simply pass string inputs into that function directly one at a time.

2024-08-04 20:17 UTC, tianyizheng02 commented on pittapi/gym.py
> +def get_gym_information(gym_name: str) -> Gym | None:
Nit: could we rename this function to `get_gym_info`, so that it's consistent with `get_all_gyms_info`?

2024-08-08 03:42 UTC, Steven-Jarmell commented
Hey @csidarous, the commit message that you just sent has a typo at the beginning. Let's be more careful about this and hold a high bar.

2024-08-08 03:45 UTC, Steven-Jarmell commented
Also considering that there are 8 commits, once Tianyi is satisfied, let's rebase and squash them into one commit.

2024-08-08 05:21 UTC, tianyizheng02 commented on pittapi/gym.py
> +    return None
```suggestion
    return None
```
Nit: I believe you can remove the else-statement entirely here and it'll do the same thing

2024-08-08 05:21 UTC, tianyizheng02 commented on pittapi/gym.py
> +    gyms = []
```suggestion
```
This line is unnecessary now that you create the list with a list comprehension later on

2024-08-08 05:23 UTC, tianyizheng02 commented
```
Name                  Stmts   Miss Branch BrPart  Cover   Missing
-----------------------------------------------------------------
...
pittapi/gym.py           40      0     10      0   100%
```
Nice, 100% coverage 👍

2024-08-08 05:27 UTC, tianyizheng02 commented on pittapi/gym.py
> +    def from_text(cls, text: str) -> "Gym":
```suggestion
from typing import NamedTuple, Self

GYM_URL = "https://connect2concepts.com/connect2/?type=bar&key=17c2cbcb-ec92-4178-a5f5-c4860330aea0"

GYM_NAMES = [
    "Baierl Rec Center",
    "Bellefield Hall: Fitness Center & Weight Room",
    "Bellefield Hall: Court & Dance Studio",
    "Trees Hall: Fitness Center",
    "Trees Hall: Courts",
    "Trees Hall: Racquetball Courts & Multipurpose Room",
    "William Pitt Union",
    "Pitt Sports Dome",
]


class Gym(NamedTuple):
    name: str
    date: str
    count: int
    percentage: int

    @classmethod
    def from_text(cls, text: str) -> Self:
```
I see that you annotated the return type for `from_text` as `"Gym"`. FYI, this isn't wrong and does work correctly, but I think a slightly better solution would be to use the [`Self` type from the `typing` module](https://docs.python.org/3/library/typing.html#typing.Self), which allows us to specify the type without directly referencing the class name.

2024-08-08 05:33 UTC, tianyizheng02 commented on pittapi/gym.py
> +    def from_text(cls, text: str) -> "Gym":
NVM, seems like that feature isn't supported in `typing` until 3.11 😓

2024-08-08 05:34 UTC, tianyizheng02 approved these changes

2024-08-08 05:34 UTC, merged

2024-08-08 05:35 UTC, tianyizheng02 commented
Thanks for all your work, @csidarous!