#208 Updating readme to add badge
Pitt-CSC/PittAPI pull request #209
Opened 2024-12-03 11:51 UTC by Conor0Callaghan

Add badge to README as per #208 part 1

2024-12-03 18:43 UTC, rohit-ganguly reviewed
Thanks for adding the shield, that's awesome. I think it would be useful to add a short section around installation via pip/pipenv too towards the start of the doc!

2024-12-09 11:55 UTC, tianyizheng02 requested changes
For convenience, is it possible to have the badge be a clickable link to PittAPI's PyPI page?

2024-12-09 14:55 UTC, Conor0Callaghan commented
> Thanks for adding the shield, that's awesome. I think it would be useful to add a short section around installation via pip/pipenv too towards the start of the doc!

hopefully that's a good start!

2024-12-20 05:06 UTC, tianyizheng02 requested changes, later dismissed
Personally I don't think we need to include instructions for setting up a virtual environment in the Installation section. I think it's better to leave that choice of using a virtual environment (and how to set one up) up to the user, rather than recommending it with `pipenv` specifically. I feel that it's enough to explain how to install the package itself through `pip`.

2024-12-20 05:06 UTC, tianyizheng02 commented on README.md
> +Pitt API can be installed using the python package manager ``pip``. To make your development easier, you can run the pip commands in a virtual environment.
```suggestion
The Pitt API can be installed using the Python package manager `pip`. To make your development easier, you can run the pip commands in a virtual environment. 
```

2024-12-22 00:27 UTC, timparenti commented
> Personally I don't think we need to include instructions for setting up a virtual environment in the Installation section. I think it's better to leave that choice of using a virtual environment (and how to set one up) up to the user

Since many of the intended audience for this API are beginners and learners, I disagree.  I think it's important to explicitly let folks at that level know of the option so that they can make an informed decision on whether they want to "pollute" their default dependency tree, or at least be aware that that could happen in the likely case they want to keep something else separate later.

Now, could this text maybe be a bit clearer that a virtual environment is not a _requirement_, but merely a _best practice_ that's worth considering?  Absolutely.  Should it instead just point people to good write-ups on how to set up the most common types instead of providing step-by-step instructions for one option ourselves?  Perhaps.  But, to my mind, that adds a dose of unnecessary friction, and for something this simple, I don't think the proposed instructions are harmful as written.

Beginners have to be introduced to these concepts somehow so they can experiment and, as is your goal, ultimately make their own choices.  I think this project is a _fantastic_ low-stakes place for folks to encounter and weigh these considerations, if they haven't before.

2024-12-23 15:51 UTC, azharichenko commented on README.md
> +2. Run the commands ``pipenv install`` and ``pipenv shell`` to create and setup the virtual environment.
```suggestion
2. Run the commands ``pipenv sync --dev`` and ``pipenv shell`` to create and setup the virtual environment.
```

2024-12-23 15:52 UTC, azharichenko approved these changes

2024-12-23 15:53 UTC, merged